from . import db
from flask_login import UserMixin

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    fullName = db.Column(db.String(150))
    username = db.Column(db.String(150))
    email = db.Column(db.String(150), unique=True)
    emailauth = db.Column(db.String()) # Used to verify email address using autogenerated number
    emailauthexp = db.Column(db.Integer()) # Used for checking expiration date for email verification
    emailauthattempts = db.Column(db.Integer())
    resetpassword = db.Column(db.String()) # Used to reset password using autogenerated number
    resetpasswordexp = db.Column(db.Integer()) # Used for checking expiration date for password reset
    password = db.Column(db.String(150))
    testlevel = db.Column(db.String(10))

class Players(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), unique=True)
    ranking = db.Column(db.Integer())
    gamesplayed = db.Column(db.Integer())
    gamesIds = db.Column(db.String())
    rankingHistory = db.Column(db.Integer())

class Games(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    type = db.Column(db.String())
    player1 = db.Column(db.String(150))
    player1elo = db.Column(db.Integer())
    player1elodelta = db.Column(db.Integer())
    player2 = db.Column(db.String(150))
    player2elo = db.Column(db.Integer())
    player2elodelta = db.Column(db.Integer())
    winner = db.Column(db.String(150))
